/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkoutRouteImport } from './routes/_app/workout'
import { Route as AppSquadsRouteImport } from './routes/_app/squads'
import { Route as AppScanRouteImport } from './routes/_app/scan'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPricingRouteImport } from './routes/_app/pricing'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppDietRouteImport } from './routes/_app/diet'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as ApiPublicFirebaseConfigRouteImport } from './routes/api/public/firebase-config'
import { Route as AppSquadsSquadIdRouteImport } from './routes/_app/squads.$squadId'
import { Route as AppSquadsJoinCodeRouteImport } from './routes/_app/squads.join.$code'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkoutRoute = AppWorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => AppRoute,
} as any)
const AppSquadsRoute = AppSquadsRouteImport.update({
  id: '/squads',
  path: '/squads',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingRoute = AppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppDietRoute = AppDietRouteImport.update({
  id: '/diet',
  path: '/diet',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFirebaseConfigRoute = ApiPublicFirebaseConfigRouteImport.update({
  id: '/api/public/firebase-config',
  path: '/api/public/firebase-config',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSquadsSquadIdRoute = AppSquadsSquadIdRouteImport.update({
  id: '/$squadId',
  path: '/$squadId',
  getParentRoute: () => AppSquadsRoute,
} as any)
const AppSquadsJoinCodeRoute = AppSquadsJoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => AppSquadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/chat': typeof AppChatRoute
  '/diet': typeof AppDietRoute
  '/home': typeof AppHomeRoute
  '/onboarding': typeof AppOnboardingRoute
  '/pricing': typeof AppPricingRoute
  '/profile': typeof AppProfileRoute
  '/scan': typeof AppScanRoute
  '/squads': typeof AppSquadsRouteWithChildren
  '/workout': typeof AppWorkoutRoute
  '/squads/$squadId': typeof AppSquadsSquadIdRoute
  '/api/public/firebase-config': typeof ApiPublicFirebaseConfigRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/squads/join/$code': typeof AppSquadsJoinCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/chat': typeof AppChatRoute
  '/diet': typeof AppDietRoute
  '/home': typeof AppHomeRoute
  '/onboarding': typeof AppOnboardingRoute
  '/pricing': typeof AppPricingRoute
  '/profile': typeof AppProfileRoute
  '/scan': typeof AppScanRoute
  '/squads': typeof AppSquadsRouteWithChildren
  '/workout': typeof AppWorkoutRoute
  '/squads/$squadId': typeof AppSquadsSquadIdRoute
  '/api/public/firebase-config': typeof ApiPublicFirebaseConfigRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/squads/join/$code': typeof AppSquadsJoinCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/diet': typeof AppDietRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/pricing': typeof AppPricingRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/scan': typeof AppScanRoute
  '/_app/squads': typeof AppSquadsRouteWithChildren
  '/_app/workout': typeof AppWorkoutRoute
  '/_app/squads/$squadId': typeof AppSquadsSquadIdRoute
  '/api/public/firebase-config': typeof ApiPublicFirebaseConfigRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/_app/squads/join/$code': typeof AppSquadsJoinCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/chat'
    | '/diet'
    | '/home'
    | '/onboarding'
    | '/pricing'
    | '/profile'
    | '/scan'
    | '/squads'
    | '/workout'
    | '/squads/$squadId'
    | '/api/public/firebase-config'
    | '/api/public/razorpay-webhook'
    | '/squads/join/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/chat'
    | '/diet'
    | '/home'
    | '/onboarding'
    | '/pricing'
    | '/profile'
    | '/scan'
    | '/squads'
    | '/workout'
    | '/squads/$squadId'
    | '/api/public/firebase-config'
    | '/api/public/razorpay-webhook'
    | '/squads/join/$code'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/chat'
    | '/_app/diet'
    | '/_app/home'
    | '/_app/onboarding'
    | '/_app/pricing'
    | '/_app/profile'
    | '/_app/scan'
    | '/_app/squads'
    | '/_app/workout'
    | '/_app/squads/$squadId'
    | '/api/public/firebase-config'
    | '/api/public/razorpay-webhook'
    | '/_app/squads/join/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicFirebaseConfigRoute: typeof ApiPublicFirebaseConfigRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workout': {
      id: '/_app/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof AppWorkoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/squads': {
      id: '/_app/squads'
      path: '/squads'
      fullPath: '/squads'
      preLoaderRoute: typeof AppSquadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan': {
      id: '/_app/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing': {
      id: '/_app/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AppPricingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diet': {
      id: '/_app/diet'
      path: '/diet'
      fullPath: '/diet'
      preLoaderRoute: typeof AppDietRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/firebase-config': {
      id: '/api/public/firebase-config'
      path: '/api/public/firebase-config'
      fullPath: '/api/public/firebase-config'
      preLoaderRoute: typeof ApiPublicFirebaseConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/squads/$squadId': {
      id: '/_app/squads/$squadId'
      path: '/$squadId'
      fullPath: '/squads/$squadId'
      preLoaderRoute: typeof AppSquadsSquadIdRouteImport
      parentRoute: typeof AppSquadsRoute
    }
    '/_app/squads/join/$code': {
      id: '/_app/squads/join/$code'
      path: '/join/$code'
      fullPath: '/squads/join/$code'
      preLoaderRoute: typeof AppSquadsJoinCodeRouteImport
      parentRoute: typeof AppSquadsRoute
    }
  }
}

interface AppSquadsRouteChildren {
  AppSquadsSquadIdRoute: typeof AppSquadsSquadIdRoute
  AppSquadsJoinCodeRoute: typeof AppSquadsJoinCodeRoute
}

const AppSquadsRouteChildren: AppSquadsRouteChildren = {
  AppSquadsSquadIdRoute: AppSquadsSquadIdRoute,
  AppSquadsJoinCodeRoute: AppSquadsJoinCodeRoute,
}

const AppSquadsRouteWithChildren = AppSquadsRoute._addFileChildren(
  AppSquadsRouteChildren,
)

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppDietRoute: typeof AppDietRoute
  AppHomeRoute: typeof AppHomeRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPricingRoute: typeof AppPricingRoute
  AppProfileRoute: typeof AppProfileRoute
  AppScanRoute: typeof AppScanRoute
  AppSquadsRoute: typeof AppSquadsRouteWithChildren
  AppWorkoutRoute: typeof AppWorkoutRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppDietRoute: AppDietRoute,
  AppHomeRoute: AppHomeRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPricingRoute: AppPricingRoute,
  AppProfileRoute: AppProfileRoute,
  AppScanRoute: AppScanRoute,
  AppSquadsRoute: AppSquadsRouteWithChildren,
  AppWorkoutRoute: AppWorkoutRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicFirebaseConfigRoute: ApiPublicFirebaseConfigRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
